### ISSUE TITLE
 Error: 'box' is not an exported object from 'namespace:shinydashboardPlus'

### ISSUE THREAD

**Issue by DEQecostel** [OR-Dept-Environmental-Quality/HAB_Shiny_app#2]
https://github.com/OR-Dept-Environmental-Quality/HAB_Shiny_app/blob/e612e9a65e3142a83323707ee2273aba0169637f/app.R#L127

I got this error when I tried to run the app locally. This is because the box function is from the shinydashboard package, not shinydashboardPlus.

**Comment by DEQecostel** [comment]
the box function is in the newest developer version of the shinydashboardPlus package, but not the version installed from CRAN. use the highlighted installation instead of the CRAN installation. 
![image](https://user-images.githubusercontent.com/27024206/104399993-ab7a0f00-5506-11eb-96e7-2827148fdff4.png)

**Comment by DEQygrund** [comment]
I will build in a package check in the codes in the future.
