### ISSUE TITLE
 Error in .rasterObjectFromFile: Cannot create a RasterLayer object from this file. (file does not exist)   

### ISSUE THREAD

**Issue by DEQecostel** [OR-Dept-Environmental-Quality/HAB_Shiny_app#4]
https://github.com/OR-Dept-Environmental-Quality/HAB_Shiny_app/blob/e612e9a65e3142a83323707ee2273aba0169637f/app.R#L392

New error, though now when I run the code, a pop up window is generated and I can see the basic shiny app components, then it disappears and gives this error. 

Looks like I am not creating the raster (.tif File)  in the local file being referenced?

**Comment by DEQygrund** [comment]
The complete path has been provided.
